currentLine = function() {
  return Router.current().params.line;
};

currentStations = function () {
  return stations[currentLine()];
};

stations = {
  "Red Line - Eastbound": [
    {name: 'Alewife'},
    {name: 'Davis'},
    {name: 'Porter Square'},
    {name: 'Harvard Square'},
    {name: 'Central Square'},
    {name: 'Kendall'},
    {name: 'Charles/MGH'},
    {name: 'Park Street'},
    {name: 'Downtown Crossing'},
    {name: 'South Station'},
    {name: 'Broadway'},
    {name: 'Andrew'},
    {name: 'JFK/UMass'},
    {name: 'North Quincy'},
    {name: 'Wollaston'},
    {name: 'Quincy Center'},
    {name: 'Quincy Adams'},
    {name: 'Braintree'},
    {name: 'Savin Hill'},
    {name: 'Fields Corner'},
    {name: 'Shawmut'},
    {name: 'Ashmont'}
  ],
  "Red Line - Westbound": [
    {name: 'Alewife'},
    {name: 'Davis'},
    {name: 'Porter Square'},
    {name: 'Harvard Square'},
    {name: 'Central Square'},
    {name: 'Kendall'},
    {name: 'Charles/MGH'},
    {name: 'Park Street'},
    {name: 'Downtown Crossing'},
    {name: 'South Station'},
    {name: 'Broadway'},
    {name: 'Andrew'},
    {name: 'JFK/UMass'},
    {name: 'North Quincy'},
    {name: 'Wollaston'},
    {name: 'Quincy Center'},
    {name: 'Quincy Adams'},
    {name: 'Braintree'},
    {name: 'Savin Hill'},
    {name: 'Fields Corner'},
    {name: 'Shawmut'},
    {name: 'Ashmont'}
  ],
  "Orange Line - Eastbound": [
    {name: "Oak Grove"},
    {name: "Malden Center"},
    {name: "Wellington"},
    {name: "Assembly"},
    {name: "Sullivan Square"},
    {name: "Community College"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "State Street"},
    {name: "Downtown Crossing"},
    {name: "Chinatown"},
    {name: "Tufts Medical Center"},
    {name: "Back Bay"},
    {name: "Massachusetts Ave."},
    {name: "Ruggles"},
    {name: "Roxbury Crossing"},
    {name: "Jackson Square"},
    {name: "Stony Brook"},
    {name: "Green Street"},
    {name: "Forest Hills"}
  ],
  "Orange Line - Westbound": [
    {name: "Oak Grove"},
    {name: "Malden Center"},
    {name: "Wellington"},
    {name: "Assembly"},
    {name: "Sullivan Square"},
    {name: "Community College"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "State Street"},
    {name: "Downtown Crossing"},
    {name: "Chinatown"},
    {name: "Tufts Medical Center"},
    {name: "Back Bay"},
    {name: "Massachusetts Ave."},
    {name: "Ruggles"},
    {name: "Roxbury Crossing"},
    {name: "Jackson Square"},
    {name: "Stony Brook"},
    {name: "Green Street"},
    {name: "Forest Hills"}
  ],
  "Blue Line - Northeastbound": [
    {name: 'Wonderland'},
    {name: 'Revere Beach'},
    {name: 'Beachmont'},
    {name: 'Suffolk Downs'},
    {name: 'Orient Heights'},
    {name: 'Wood Island'},
    {name: 'Airport'},
    {name: 'Maverick'},
    {name: 'Aquarium'},
    {name: 'State'},
    {name: 'Bowdoin'}
  ],
  "Blue Line - Southwestbound": [
    {name: 'Wonderland'},
    {name: 'Revere Beach'},
    {name: 'Beachmont'},
    {name: 'Suffolk Downs'},
    {name: 'Orient Heights'},
    {name: 'Wood Island'},
    {name: 'Airport'},
    {name: 'Maverick'},
    {name: 'Aquarium'},
    {name: 'State'},
    {name: 'Bowdoin'}
  ],
  "Green Line - Northbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Blandford Street"},
    {name: "Boston Univ. East"},
    {name: "Boston Univ. Central"},
    {name: "Boston Univ. West"},
    {name: "Saint Paul Street"},
    {name: "Pleasant Street"},
    {name: "Babcock Street"},
    {name: "Packards Corner"},
    {name: "Harvard Ave."},
    {name: "Griggs Street"},
    {name: "Allston Street"},
    {name: "Warren Street"},
    {name: "Washington Street"},
    {name: "Sutherland Road"},
    {name: "Chiswick Road"},
    {name: "Chestnut Hill Ave."},
    {name: "South Street"},
    {name: "Boston College"}
  ],
  "Green Line - Southbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Blandford Street"},
    {name: "Boston Univ. East"},
    {name: "Boston Univ. Central"},
    {name: "Boston Univ. West"},
    {name: "Saint Paul Street"},
    {name: "Pleasant Street"},
    {name: "Babcock Street"},
    {name: "Packards Corner"},
    {name: "Harvard Ave."},
    {name: "Griggs Street"},
    {name: "Allston Street"},
    {name: "Warren Street"},
    {name: "Washington Street"},
    {name: "Sutherland Road"},
    {name: "Chiswick Road"},
    {name: "Chestnut Hill Ave."},
    {name: "South Street"},
    {name: "Boston College"}
  ],
  "Yellow Line - Northbound": [
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Saint Mary Street"},
    {name: "Hawes Street"},
    {name: "Kent Street"},
    {name: "Saint Paul Street"},
    {name: "Coolidge Corner"},
    {name: "Summit Ave."},
    {name: "Brandon Hall"},
    {name: "Fairbanks Street"},
    {name: "Washington Square"},
    {name: "Tappan Street"},
    {name: "Dean Road"},
    {name: "Englewood Ave."},
    {name: "Cleveland Circle"}
  ],
  "Yellow Line - Southbound": [
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Saint Mary Street"},
    {name: "Hawes Street"},
    {name: "Kent Street"},
    {name: "Saint Paul Street"},
    {name: "Coolidge Corner"},
    {name: "Summit Ave."},
    {name: "Brandon Hall"},
    {name: "Fairbanks Street"},
    {name: "Washington Square"},
    {name: "Tappan Street"},
    {name: "Dean Road"},
    {name: "Englewood Ave."},
    {name: "Cleveland Circle"}
  ],
  "Yellow Line Rush Hour Virginia - Northbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Fenway"},
    {name: "Longwood"},
    {name: "Brookline Village"},
    {name: "Brookline Hills"},
    {name: "Beaconsfield"},
    {name: "Reservoir"},
    {name: "Chestnut Hill"},
    {name: "Newton Centre"},
    {name: "Newton Highlands"},
    {name: "Eliot"},
    {name: "Waban"},
    {name: "Woodland"},
    {name: "Riverside"}
  ],
  "Yellow Line Rush Hour Virginia - Southbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Fenway"},
    {name: "Longwood"},
    {name: "Brookline Village"},
    {name: "Brookline Hills"},
    {name: "Beaconsfield"},
    {name: "Reservoir"},
    {name: "Chestnut Hill"},
    {name: "Newton Centre"},
    {name: "Newton Highlands"},
    {name: "Eliot"},
    {name: "Waban"},
    {name: "Woodland"},
    {name: "Riverside"}
  ],
  "Yellow Line Rush Hour Maryland - Northbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ],
  "Yellow Line Rush Hour Maryland - Southbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ],
  "Silver Line - Eastbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ],
  "Silver Line - Westbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ]
};
