currentLine = function() {
  return Router.current().params.line;
};

currentStations = function () {
  return stations[currentLine()];
};

stations = {
  "Red Line - Eastbound": [
    {name: 'Glenmont'},
    {name: 'Wheaton'},
    {name: 'Forest Glen'},
    {name: 'Silver Spring'},
    {name: 'Takoma'},
    {name: 'Fort Totten'},
    {name: 'Brookland-CUA'},
    {name: 'Rhode Island Ave'},
    {name: 'NoMa-Gallaudet U'},
    {name: 'Union Station'},
    {name: 'Judiciary Sq'},
    {name: 'Gallery Place'},
    {name: 'Metro Center'},
    {name: 'Farragut North'},
    {name: 'Dupont Circle'},
    {name: 'Woodley Park'},
    {name: 'Cleveland Park'},
    {name: 'Van Ness-UDC'},
    {name: 'Tenleytown-AU'},
    {name: 'Friendship Heights'},
    {name: 'Bethesda'},
    {name: 'Medical Center'},
    {name: 'Grosvenor-Strathmore'},
    {name: 'White Flint'},
    {name: 'Twinbrook'},
    {name: 'Rockville'},
    {name: 'Shady Grove'}
  ],
  "Red Line - Westbound": [
    {name: 'Alewife'},
    {name: 'Davis'},
    {name: 'Porter Square'},
    {name: 'Harvard Square'},
    {name: 'Central Square'},
    {name: 'Kendall'},
    {name: 'Charles/MGH'},
    {name: 'Park Street'},
    {name: 'Downtown Crossing'},
    {name: 'South Station'},
    {name: 'Broadway'},
    {name: 'Andrew'},
    {name: 'JFK/UMass'},
    {name: 'North Quincy'},
    {name: 'Wollaston'},
    {name: 'Quincy Center'},
    {name: 'Quincy Adams'},
    {name: 'Braintree'},
    {name: 'Savin Hill'},
    {name: 'Fields Corner'},
    {name: 'Shawmut'},
    {name: 'Ashmont'}
  ],
  "Orange Line - Eastbound": [
    {name: "New Carrolton"},
    {name: "Landover"},
    {name: "Cheverly"},
    {name: "Deanwood"},
    {name: "Minnesota Ave"},
    {name: "Stadium-Armory"},
    {name: "Potomac Ave"},
    {name: "Eastern Market"},
    {name: "Capitol South"},
    {name: "Federal Center SW"},
    {name: "L'Enfant Plaza"},
    {name: "Smithsonian"},
    {name: "Federal Triangle"},
    {name: "Metro Center"},
    {name: "McPherson Sq"},
    {name: "Farragut West"},
    {name: "Foggy Bottom-GWU"},
    {name: "Rosslyn"},
    {name: "Court House"},
    {name: "Clarendon"},
    {name: "Virginia Sq-GMU"},
    {name: "Ballston-MU"},
    {name: "East Falls Church"}
    {name: "West Falls Church"},
    {name: "Dunn Loring"},
    {name: "Vienna"}
  ],
  "Orange Line - Westbound": [
    {name: "Oak Grove"},
    {name: "Malden Center"},
    {name: "Wellington"},
    {name: "Assembly"},
    {name: "Sullivan Square"},
    {name: "Community College"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "State Street"},
    {name: "Downtown Crossing"},
    {name: "Chinatown"},
    {name: "Tufts Medical Center"},
    {name: "Back Bay"},
    {name: "Massachusetts Ave."},
    {name: "Ruggles"},
    {name: "Roxbury Crossing"},
    {name: "Jackson Square"},
    {name: "Stony Brook"},
    {name: "Green Street"},
    {name: "Forest Hills"}
  ],
  "Blue Line - Northeastbound": [
    {name: 'Largo Town Center'},
    {name: 'Morgan Blvd'},
    {name: 'Addison Rd'},
    {name: 'Capitol Heights'},
    {name: 'Benning Rd'},
    {name: 'Stadium-Armory'},
    {name: 'Potomac Ave'},
    {name: 'Eastern Market'},
    {name: 'Capitol South'},
    {name: 'Federal Center SW'},
    {name: "L'Enfant Plaza"},
    {name: "Smithsonian"},
    {name: "Federal Triangle"},
    {name: "Metro Center"},
    {name: "McPherson Sq"},
    {name: "Farragut West"},
    {name: "Foggy Bottom-GWU"},
    {name: "Rosslyn"},
    {name: "Arlington Cemetery"},
    {name: "Pentagon"},
    {name: "Pentagon City"},
    {name: "Crystal City"},
    {name: "Ronald Reagan Washington National Airport"},
    {name: "Braddock Rd"},
    {name: "King St-Old Town"},
    {name: "Van Dorn St"},
    {name: "Franconia-Springfield"}
  ],
  "Blue Line - Southwestbound": [
    {name: 'Wonderland'},
    {name: 'Revere Beach'},
    {name: 'Beachmont'},
    {name: 'Suffolk Downs'},
    {name: 'Orient Heights'},
    {name: 'Wood Island'},
    {name: 'Airport'},
    {name: 'Maverick'},
    {name: 'Aquarium'},
    {name: 'State'},
    {name: 'Bowdoin'}
  ],
  "Green Line - Northbound": [
    {name: "Greenbelt"},
    {name: "College Park-U of Md"},
    {name: "Prince George's Plaza"},
    {name: "West Hyattsville"},
    {name: "Fort Totten"},
    {name: "Georgia Ave-Petworth"},
    {name: "Columbia Heights"},
    {name: "U St"},
    {name: "Shaw-Howard U"},
    {name: "Mt Vernon Sq"},
    {name: "Gallery Place"},
    {name: "Archives"},
    {name: "L'Enfant Plaza"},
    {name: "Waterfront"},
    {name: "Navy Yard-Ballpark"},
    {name: "Anacostia"},
    {name: "Congress Heights"},
    {name: "Southern Ave"},
    {name: "Naylor Rd"},
    {name: "Suitland"},
    {name: "Branch Ave"}
  ],
  "Green Line - Southbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Blandford Street"},
    {name: "Boston Univ. East"},
    {name: "Boston Univ. Central"},
    {name: "Boston Univ. West"},
    {name: "Saint Paul Street"},
    {name: "Pleasant Street"},
    {name: "Babcock Street"},
    {name: "Packards Corner"},
    {name: "Harvard Ave."},
    {name: "Griggs Street"},
    {name: "Allston Street"},
    {name: "Warren Street"},
    {name: "Washington Street"},
    {name: "Sutherland Road"},
    {name: "Chiswick Road"},
    {name: "Chestnut Hill Ave."},
    {name: "South Street"},
    {name: "Boston College"}
  ],
  "Yellow Line - Northbound": [
    {name: "Greenbelt"},
    {name: "College Park-U of Md"},
    {name: "Prince George's Plaza"},
    {name: "West Hyattsville"},
    {name: "Fort Totten"},
    {name: "Georgia Ave-Petworth"},
    {name: "Columbia Heights"},
    {name: "U St"},
    {name: "Shaw-Howard U"},
    {name: "Mt Vernon Sq"},
    {name: "Gallery Place"},
    {name: "Archives"},
    {name: "L'Enfant Plaza"},
    {name: "Pentagon"},
    {name: "Pentagon City"},
    {name: "Crystal City"},
    {name: "Ronald Reagan Washington National Airport"},
    {name: "Braddock Rd"},
    {name: "King St-Old Town"},
    {name: "Eisenhower Ave"},
    {name: "Huntington"}
  ],
  "Yellow Line - Southbound": [
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Saint Mary Street"},
    {name: "Hawes Street"},
    {name: "Kent Street"},
    {name: "Saint Paul Street"},
    {name: "Coolidge Corner"},
    {name: "Summit Ave."},
    {name: "Brandon Hall"},
    {name: "Fairbanks Street"},
    {name: "Washington Square"},
    {name: "Tappan Street"},
    {name: "Dean Road"},
    {name: "Englewood Ave."},
    {name: "Cleveland Circle"}
  ],
  "Yellow Line Rush Hour Virginia - Northbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Fenway"},
    {name: "Longwood"},
    {name: "Brookline Village"},
    {name: "Brookline Hills"},
    {name: "Beaconsfield"},
    {name: "Reservoir"},
    {name: "Chestnut Hill"},
    {name: "Newton Centre"},
    {name: "Newton Highlands"},
    {name: "Eliot"},
    {name: "Waban"},
    {name: "Woodland"},
    {name: "Riverside"}
  ],
  "Yellow Line Rush Hour Virginia - Southbound": [
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Hynes Convention Center"},
    {name: "Kenmore"},
    {name: "Fenway"},
    {name: "Longwood"},
    {name: "Brookline Village"},
    {name: "Brookline Hills"},
    {name: "Beaconsfield"},
    {name: "Reservoir"},
    {name: "Chestnut Hill"},
    {name: "Newton Centre"},
    {name: "Newton Highlands"},
    {name: "Eliot"},
    {name: "Waban"},
    {name: "Woodland"},
    {name: "Riverside"}
  ],
  "Yellow Line Rush Hour Maryland - Northbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ],
  "Yellow Line Rush Hour Maryland - Southbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ],
  "Silver Line - Eastbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ],
  "Silver Line - Westbound": [
    {name: "Lechmere"},
    {name: "Science Park"},
    {name: "North Station"},
    {name: "Haymarket"},
    {name: "Park Street"},
    {name: "Boylston"},
    {name: "Arlington"},
    {name: "Copley"},
    {name: "Prudential"},
    {name: "Symphony"},
    {name: "Northeastern University"},
    {name: "Museum of Fine Arts"},
    {name: "Longwood Medical Area"},
    {name: "Brigham Circle"},
    {name: "Fenwood Road"},
    {name: "Mission Park"},
    {name: "Riverway"},
    {name: "Back of the Hill"},
    {name: "Heath Street"}
  ]
};
